In [2]:
import sklearn

In [3]:
sklearn.__version__

'1.4.2'

In [4]:
# Update command
# !conda update scikit-learn
# pip install -U scikit-learn


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -g


Cleansing
    Nan
    Deduplicate
Preprocessing
    * encode
            ML can work with non number on count to make popularlity
            CART classification a regression tree
            JW48 (java)
    * Scale
    * Normalize
        white training
Imputation เติม คืน ค่าทเดิมมี่หายไป
    * 10/100 ควร drop แต่หากมีความสำคัญ ต้องเก็บ
Feature Engineering
* Feature Extraction (PCA) เข้ารหัส
* Feature Selection ค่ายังมีหน่วยอยู่

### Preprocessing

##### Oridinal Encoding ตัวเลข ความหมายเชิงลำดับ

In [5]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder

In [6]:
encoder = OrdinalEncoder()

In [7]:
X = [['A'],['B'],['C'],['D']]

In [8]:
encoder.fit(X)

OrdinalEncoder()

In [9]:
X_ = encoder.transform(X)
# พยายามเรียงลำดับ จากตัวเลข unicode ของ string

In [10]:
X_

array([[0.],
       [1.],
       [2.],
       [3.]])

In [11]:
# ตัวแปรในตัวมันเอง
encoder.categories_

[array(['A', 'B', 'C', 'D'], dtype=object)]

In [12]:
X = [['A', 10],['B', 9.5],['C', 8],['D', 16]]

In [13]:
encoder.fit(X)

OrdinalEncoder()

In [14]:
X_ = encoder.transform(X)

In [15]:
X_
# สนใจลำดับ ไม่ได้สนใจระยะห่าง

array([[0., 2.],
       [1., 1.],
       [2., 0.],
       [3., 3.]])

In [16]:
encoder.categories_

[array(['A', 'B', 'C', 'D'], dtype=object),
 array([8, 9.5, 10, 16], dtype=object)]

In [17]:
encoder.inverse_transform(X_)

array([['A', 10],
       ['B', 9.5],
       ['C', 8],
       ['D', 16]], dtype=object)

#### Label Encoder

In [33]:
Labencoder = LabelEncoder()

NameError: name 'LabelEncoder' is not defined

In [31]:
# label มีมิติเดียว จะไม่มีการซ้อนลิสต์ ไม่มีลำดับ
Y = ['Ant','Bat','Cat','Dog']

In [23]:
Y

['Ant', 'Bat', 'Cat', 'Dog']

In [24]:
encoder.fit(Y)

ValueError: Expected 2D array, got 1D array instead:
array=['Ant' 'Bat' 'Cat' 'Dog'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
Y_ = encoder.transform(Y)

#### On-hot Encoding

In [34]:
from sklearn.preprocessing import OneHotEncoder

In [35]:
encoder = OneHotEncoder()

In [37]:
X = [['Ant'],['Bat'],['Cat'],['Ant'],['Bat'],['Cat']]

In [38]:
encoder.fit(X)

OneHotEncoder()

In [39]:
X_ = encoder.transform(X)

In [40]:
X_

<6x3 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [41]:
X_.todense()

matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [42]:
encoder.categories_

[array(['Ant', 'Bat', 'Cat'], dtype=object)]

In [43]:
encoder.inverse_transform(X_)

array([['Ant'],
       ['Bat'],
       ['Cat'],
       ['Ant'],
       ['Bat'],
       ['Cat']], dtype=object)

In [ ]:
##### one-hot = dummy variable

In [44]:
import pandas as pd

In [47]:
df = pd.DataFrame(X, columns=['animal'])

In [48]:
df = pd.get_dummies(X)

TypeError: unhashable type: 'list'

#### MultiLabel Binaryrizer
มีอะไรบ้าง หรือไม่มี 1/0

In [49]:
from sklearn.preprocessing import MultiLabelBinarizer

In [50]:
encoder = MultiLabelBinarizer()

In [51]:
X = [['sci-fi','comedy'],
     ['comedy'],
     ['drama','romance'],
     ['sci-fi','drama','action']]

In [52]:
encoder.fit(X)

MultiLabelBinarizer()

In [53]:
X_ = encoder.transform(X)

In [54]:
X_

array([[0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [1, 0, 1, 0, 1]])

In [55]:
encoder.classes_

array(['action', 'comedy', 'drama', 'romance', 'sci-fi'], dtype=object)

#### K Bins Discretizer


In [56]:
from sklearn.preprocessing import KBinsDiscretizer

In [57]:
X = [[10],[11],[12],[16],[21],[22],[35]]

In [66]:
encoder = KBinsDiscretizer(n_bins=3)

In [67]:
encoder.fit(X)

KBinsDiscretizer(n_bins=3)

In [68]:
X_ = encoder.transform(X)

In [69]:
X_

<7x3 sparse matrix of type '<class 'numpy.float64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [70]:
X_.todense()

matrix([[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 1.],
        [0., 0., 1.]])

In [71]:
encoder = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='quantile')

In [72]:
encoder.fit(X)

KBinsDiscretizer(encode='ordinal', n_bins=3)

In [73]:
X_ = encoder.transform(X)

In [74]:
X_

array([[0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [2.],
       [2.]])

In [75]:
X_.todense()

AttributeError: 'numpy.ndarray' object has no attribute 'todense'

In [59]:
encoder = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
# 3 ช่วง เล็ก กลาง ใหญ่

In [60]:
encoder.fit(X)

C:\Users\cyber\AppData\Roaming\Python\Python312\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


KBinsDiscretizer(encode='ordinal', n_bins=3, strategy='uniform')

In [61]:
X_ = encoder.transform(X)

In [63]:
X_

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [2.]])

In [65]:
X_.todense()

AttributeError: 'numpy.ndarray' object has no attribute 'todense'

## MinMax Scaler

In [76]:
from sklearn.preprocessing import MinMaxScaler

In [85]:
X = [[1],[2],[3.9],[4],[5]]

In [86]:
scaler = MinMaxScaler()

In [87]:
scaler.fit(X)

MinMaxScaler()

In [88]:
X_ = scaler.transform(X)

In [89]:
X_

array([[0.   ],
       [0.25 ],
       [0.725],
       [0.75 ],
       [1.   ]])

In [90]:
scaler.inverse_transform(X_)

array([[1. ],
       [2. ],
       [3.9],
       [4. ],
       [5. ]])

In [ ]:
## Nomalization     

In [91]:
from sklearn.preprocessing import Normalizer

In [92]:
normalizer = Normalizer()

In [93]:
X = [[4,1,2,2],
     [3,4,5,1],
     [2,3,4,5]]

In [94]:
normalizer.fit(X)

Normalizer()

In [95]:
X_ = normalizer.transform(X)

In [96]:
X_

array([[0.8       , 0.2       , 0.4       , 0.4       ],
       [0.42008403, 0.56011203, 0.70014004, 0.14002801],
       [0.27216553, 0.40824829, 0.54433105, 0.68041382]])

In [97]:
normalizer = Normalizer(norm='l1')
#manhuton distance

In [98]:
normalizer.fit(X)

Normalizer(norm='l1')

In [99]:
X_ = normalizer.transform(X)

In [100]:
X_

array([[0.44444444, 0.11111111, 0.22222222, 0.22222222],
       [0.23076923, 0.30769231, 0.38461538, 0.07692308],
       [0.14285714, 0.21428571, 0.28571429, 0.35714286]])

## Standardization การทำให้ มีน เป็น ศูนย์ และ แวเร์เรียน เป็น หนึ่ง C score

In [ ]:
from sklearn.preprocessing import StandardScaler

# Imputation

In [102]:
import numpy as np

In [103]:
X = [[np.nan, np.nan, 3], [4,1,6], [10,2,9],[10,2,9]]

In [104]:
from sklearn.impute import SimpleImputer

In [105]:
imputer = SimpleImputer(strategy='mean')

In [108]:
imputer.fit(X)

SimpleImputer()

In [109]:
X_ = imputer.transform(X)

In [110]:
X_

array([[ 8.        ,  1.66666667,  3.        ],
       [ 4.        ,  1.        ,  6.        ],
       [10.        ,  2.        ,  9.        ],
       [10.        ,  2.        ,  9.        ]])

In [119]:
imputer = SimpleImputer(strategy='most_frequency') 
imputer.fit_transform(X)

InvalidParameterError: The 'strategy' parameter of SimpleImputer must be a str among {'most_frequent', 'constant', 'median', 'mean'}. Got 'most_frequency' instead.

In [121]:
imputer = SimpleImputer(strategy='median') 
imputer.fit_transform(X)

array([[10.,  2.,  3.],
       [ 4.,  1.,  6.],
       [10.,  2.,  9.],
       [10.,  2.,  9.]])

In [124]:
imputer = SimpleImputer(strategy='constant', fill_value=-1) 
imputer.fit_transform(X) 

array([[-1., -1.,  3.],
       [ 4.,  1.,  6.],
       [10.,  2.,  9.],
       [10.,  2.,  9.]])

In [ ]:
#### KNN Imputer

# Feature Selection
## (X,) UnSupervisor
     * nan
          - remove, drop column
          - correlation 
     * duplicated col
     * low varian as 0 or only one value,
(X,Y) Supervise
     * Regression
          - corelation Pearson's ค่ากระจายให้ ลบออก
          - F-stat with in (class varian / between class) = F
          - MI Mutual informantion
     * Classification
          - X^2 CHI-Square
          - Anova
          - MI
(X,Y,ML) 
     * ML (feature importance)
     * forward strategy
     * Backward strategy (Recursive)
     * Exhaustive (All combination)
          - A, B, C

### Regression

In [125]:
from sklearn.feature_selection import r_regression, f_regression, mutual_info_regression

In [ ]:
score_func = r_regression
# score_func = f_regression
# score_func = mutual_info_regression

selector = GeneralUnivariateSelector(score_func=score_func, mod='k_best', param=5)
selector.fit(X.data, X.target)
print(selector.scores_)
print(selector.get_feature_names_out)